package kotlinx.browser.dom

import kotlinx.browser.dom.events.EventTarget

public actual abstract class Node : EventTarget()
public actual abstract class Element : Node()
public actual abstract class HTMLElement : Element()
public actual abstract class CharacterData : Node()
public actual open class Text : CharacterData()
public actual abstract class HTMLMediaElement : HTMLElement()

public actual abstract class HTMLAnchorElement : HTMLElement()
public actual abstract class HTMLAreaElement : HTMLElement()
public actual abstract class HTMLAudioElement : HTMLMediaElement()
public actual abstract class HTMLBRElement : HTMLElement()
public actual abstract class HTMLButtonElement : HTMLElement()
public actual abstract class HTMLCanvasElement : HTMLElement()
public actual abstract class HTMLDataListElement : HTMLElement()
public actual abstract class HTMLDListElement : HTMLElement()
public actual abstract class HTMLDivElement : HTMLElement()
public actual abstract class HTMLEmbedElement : HTMLElement()
public actual abstract class HTMLFieldSetElement : HTMLElement()
public actual abstract class HTMLFormElement : HTMLElement()
public actual abstract class HTMLHRElement : HTMLElement()
public actual abstract class HTMLHeadingElement : HTMLElement()
public actual abstract class HTMLIFrameElement : HTMLElement()
public actual abstract class HTMLImageElement : HTMLElement()
public actual abstract class HTMLInputElement : HTMLElement()
public actual abstract class HTMLLIElement : HTMLElement()
public actual abstract class HTMLLabelElement : HTMLElement()
public actual abstract class HTMLLegendElement : HTMLElement()
public actual abstract class HTMLMapElement : HTMLElement()
public actual abstract class HTMLMeterElement : HTMLElement()
public actual abstract class HTMLOListElement : HTMLElement()
public actual abstract class HTMLObjectElement : HTMLElement()
public actual abstract class HTMLOptGroupElement : HTMLElement()
public actual abstract class HTMLOptionElement : HTMLElement()
public actual abstract class HTMLOutputElement : HTMLElement()
public actual abstract class HTMLParagraphElement : HTMLElement()
public actual abstract class HTMLParamElement : HTMLElement()
public actual abstract class HTMLPictureElement : HTMLElement()
public actual abstract class HTMLPreElement : HTMLElement()
public actual abstract class HTMLProgressElement : HTMLElement()
public actual abstract class HTMLSelectElement : HTMLElement()
public actual abstract class HTMLSourceElement : HTMLElement()
public actual abstract class HTMLSpanElement : HTMLElement()
public actual abstract class HTMLStyleElement : HTMLElement()
public actual abstract class HTMLTableCaptionElement : HTMLElement()
public actual abstract class HTMLTableCellElement : HTMLElement()
public actual abstract class HTMLTableColElement : HTMLElement()
public actual abstract class HTMLTableElement : HTMLElement()
public actual abstract class HTMLTableRowElement : HTMLElement()
public actual abstract class HTMLTableSectionElement : HTMLElement()
public actual abstract class HTMLTextAreaElement : HTMLElement()
public actual abstract class HTMLTrackElement : HTMLElement()
public actual abstract class HTMLUListElement : HTMLElement()
public actual abstract class HTMLVideoElement : HTMLMediaElement()
